
package wsservicefibonacci;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OutputService", targetNamespace = "http://wsServiceFibonacci/", wsdlLocation = "file:/Users/yingqgu/Documents/workspace/wsClientFibonacci/wsdl/OutputService.wsdl")
public class OutputService
    extends Service
{

    private final static URL OUTPUTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(wsservicefibonacci.OutputService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = wsservicefibonacci.OutputService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/yingqgu/Documents/workspace/wsClientFibonacci/wsdl/OutputService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/yingqgu/Documents/workspace/wsClientFibonacci/wsdl/OutputService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OUTPUTSERVICE_WSDL_LOCATION = url;
    }

    public OutputService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutputService() {
        super(OUTPUTSERVICE_WSDL_LOCATION, new QName("http://wsServiceFibonacci/", "OutputService"));
    }

    /**
     * 
     * @return
     *     returns Output
     */
    @WebEndpoint(name = "OutputPort")
    public Output getOutputPort() {
        return super.getPort(new QName("http://wsServiceFibonacci/", "OutputPort"), Output.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Output
     */
    @WebEndpoint(name = "OutputPort")
    public Output getOutputPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServiceFibonacci/", "OutputPort"), Output.class, features);
    }

}
