
package wsservicefibonacci;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Output", targetNamespace = "http://wsServiceFibonacci/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Output {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGreeting", targetNamespace = "http://wsServiceFibonacci/", className = "wsservicefibonacci.GetGreeting")
    @ResponseWrapper(localName = "getGreetingResponse", targetNamespace = "http://wsServiceFibonacci/", className = "wsservicefibonacci.GetGreetingResponse")
    public String getGreeting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateFibonacci", targetNamespace = "http://wsServiceFibonacci/", className = "wsservicefibonacci.CalculateFibonacci")
    @ResponseWrapper(localName = "calculateFibonacciResponse", targetNamespace = "http://wsServiceFibonacci/", className = "wsservicefibonacci.CalculateFibonacciResponse")
    public String calculateFibonacci(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
